#Stages for deployment
stages:
    - pull-new-commit
    - build-container
    - deploy-container

pull-new-commit:
  stage: pull-new-commit
  script:
    - echo "Pulling new commits"
    - ssh atnog@10.0.12.91 "cd ~/git/simulator_backend; git pull;"

build-container:
    stage: build-container
    script:
        - echo "Building new image on latest commit"
        - ssh atnog@10.0.12.91 "cd ~/git/simulator_backend; sudo docker build -t sdrt/simulator_backend:$CI_COMMIT_SHORT_SHA .;"

deploy-container:
    stage: deploy-container
    script:
        - echo "Stopping and removing current container"
        - ssh atnog@10.0.12.91 "sudo docker stop simulator_backend; sudo docker rm simulator_backend; sudo docker run -d --name=simulator_backend sdrt/simulator_backend:$CI_COMMIT_SHORT_SHA;"